export type PropertyType =
  | 'Rumah'
  | 'Tanah'
  | 'Kost'
  | 'Hotel'
  | 'Homestay'
  | 'Villa'
  | 'Ruko'
  | 'Gudang'
  | 'Lainnya';

export type OfferType = 'Dijual' | 'Disewa' | 'Dijual & Disewa';

export interface Property {
  id: string;
  title: string;
  location: string;
  price: number;
  originalPrice?: number | null; // harga lama — jika diisi, HOT badge aktif otomatis
  pricePerSqm?: number;
  area?: number;
  image: string;
  propertyType: PropertyType;
  offerType: OfferType;
  bedrooms?: number;
  bathrooms?: number;
  carports?: number;
  isPremium?: boolean;   // badge PREMIUM — emas berkedip
  isFeatured?: boolean;  // badge FEATURED — biru metalik
  certificate?: 'SHM' | 'HGB' | 'SHGB' | 'Girik';
  condition?: 'Baru' | 'Bekas';
  agentName?: string;
  agentVerified?: boolean;
  views?: number;
  // derived helper — no need to store, computed on read
  // isHot = originalPrice !== null && originalPrice > price
}

/** Auto-compute isHot from price fields */
export const isHot = (p: Property): boolean =>
  !!p.originalPrice && p.originalPrice > p.price;

/** Savings percent for strike-through display */
export const savingsPercent = (p: Property): number =>
  p.originalPrice ? Math.round((1 - p.price / p.originalPrice) * 100) : 0;

export const featuredProperties: Property[] = [
  {
    id: '1',
    title: 'Rumah Modern Minimalis 3KT Cluster Condongcatur',
    location: 'Condongcatur, Sleman',
    price: 850000000,
    originalPrice: 950000000,
    pricePerSqm: 8947368,
    area: 95,
    image: '/images/listing-1.jpg',
    propertyType: 'Rumah',
    offerType: 'Dijual',
    bedrooms: 3,
    bathrooms: 2,
    carports: 1,
    isPremium: true,
    isFeatured: true,
    certificate: 'SHM',
    condition: 'Bekas',
    agentName: 'Andi Wijaya',
    agentVerified: true,
    views: 234,
  },
  {
    id: '2',
    title: 'Apartemen Studio Full Furnished Dekat UGM',
    location: 'Mlati, Sleman',
    price: 3500000,
    originalPrice: null,
    pricePerSqm: 125000,
    area: 28,
    image: '/images/listing-2.jpg',
    propertyType: 'Kost',
    offerType: 'Disewa',
    bedrooms: 1,
    bathrooms: 1,
    isFeatured: true,
    certificate: 'HGB',
    condition: 'Baru',
    agentName: 'Siti Rahayu',
    agentVerified: true,
    views: 891,
  },
  {
    id: '3',
    title: 'Villa Mewah Pemandangan Sawah 4KT Private Pool',
    location: 'Pakem, Sleman',
    price: 3500000000,
    originalPrice: 4500000000,
    pricePerSqm: 4375000,
    area: 800,
    image: '/images/listing-3.jpg',
    propertyType: 'Villa',
    offerType: 'Dijual & Disewa',
    bedrooms: 4,
    bathrooms: 4,
    isPremium: true,
    certificate: 'SHM',
    condition: 'Baru',
    agentName: 'Budi Santoso',
    agentVerified: false,
    views: 1204,
  },
];

export const latestProperties: Property[] = [
  ...featuredProperties,
  {
    id: '4',
    title: 'Rumah Klasik Elegan 4KT Cluster Premium',
    location: 'Surabaya',
    price: 650000000,
    originalPrice: null,
    pricePerSqm: 5416667,
    area: 120,
    image: '/images/listing-1.jpg',
    propertyType: 'Rumah',
    offerType: 'Dijual',
    bedrooms: 4,
    bathrooms: 3,
    carports: 2,
    isFeatured: false,
    certificate: 'SHM',
    condition: 'Bekas',
    agentName: 'Dewi Sartika',
    agentVerified: true,
    views: 567,
  },
  {
    id: '5',
    title: 'Ruko 3 Lantai Lokasi Strategis Jalan Utama',
    location: 'Bandung',
    price: 1200000000,
    originalPrice: 1450000000,
    pricePerSqm: 6000000,
    area: 200,
    image: '/images/listing-2.jpg',
    propertyType: 'Ruko',
    offerType: 'Dijual',
    isPremium: false,
    isFeatured: true,
    certificate: 'HGB',
    condition: 'Baru',
    agentName: 'Rudi Hermawan',
    agentVerified: true,
    views: 342,
  },
  {
    id: '6',
    title: 'Tanah Kavling SHM 300m² Dekat Tol Akses Mudah',
    location: 'Gamping, Sleman',
    price: 600000000,
    originalPrice: null,
    pricePerSqm: 2000000,
    area: 300,
    image: '/images/listing-3.jpg',
    propertyType: 'Tanah',
    offerType: 'Dijual',
    certificate: 'SHM',
    agentName: 'Ahmad Fajar',
    agentVerified: false,
    views: 198,
  },
  {
    id: '7',
    title: 'Kost Eksklusif AC WiFi 24 Jam Dekat Kampus',
    location: 'Depok, Sleman',
    price: 1500000,
    originalPrice: null,
    area: 18,
    image: '/images/listing-1.jpg',
    propertyType: 'Kost',
    offerType: 'Disewa',
    condition: 'Baru',
    agentName: 'Rina Kartika',
    agentVerified: true,
    views: 445,
  },
  // ── Tambahan listing per agen ──
  {
    id: '8',
    title: 'Rumah Asri 3KT Dekat Sekolah & Tol Mlati Sleman',
    location: 'Mlati, Sleman',
    price: 540000000,
    originalPrice: null,
    area: 90,
    image: '/images/listing-2.jpg',
    propertyType: 'Rumah',
    offerType: 'Dijual',
    bedrooms: 3,
    bathrooms: 2,
    carports: 1,
    certificate: 'SHM',
    condition: 'Bekas',
    agentName: 'Andi Wijaya',
    agentVerified: true,
    views: 312,
  },
  {
    id: '9',
    title: 'Tanah SHM Sleman Strategis Akses 2 Arah',
    location: 'Gamping, Sleman',
    price: 420000000,
    originalPrice: null,
    area: 200,
    image: '/images/listing-3.jpg',
    propertyType: 'Tanah',
    offerType: 'Dijual',
    certificate: 'SHM',
    agentName: 'Andi Wijaya',
    agentVerified: true,
    views: 189,
  },
  {
    id: '10',
    title: 'Apartemen 2KT Full Furnished View Kota Yogyakarta',
    location: 'Kota Yogyakarta',
    price: 4500000,
    originalPrice: null,
    area: 36,
    image: '/images/listing-1.jpg',
    propertyType: 'Kost',
    offerType: 'Disewa',
    bedrooms: 2,
    bathrooms: 1,
    condition: 'Baru',
    agentName: 'Siti Rahayu',
    agentVerified: true,
    views: 278,
  },
  {
    id: '11',
    title: 'Ruko 2 Lantai Gondokusuman Kota Yogyakarta',
    location: 'Kota Yogyakarta',
    price: 980000000,
    originalPrice: null,
    area: 120,
    image: '/images/listing-2.jpg',
    propertyType: 'Ruko',
    offerType: 'Dijual',
    certificate: 'HGB',
    condition: 'Bekas',
    agentName: 'Siti Rahayu',
    agentVerified: true,
    views: 201,
  },
  {
    id: '12',
    title: 'Villa Mewah Private Pool Pemandangan Gunung Semarang',
    location: 'Ungaran, Semarang',
    price: 4200000000,
    originalPrice: 5000000000,
    area: 600,
    image: '/images/listing-1.jpg',
    propertyType: 'Villa',
    offerType: 'Dijual',
    bedrooms: 5,
    bathrooms: 5,
    isPremium: true,
    certificate: 'SHM',
    condition: 'Baru',
    agentName: 'Budi Santoso',
    agentVerified: true,
    views: 789,
  },
  {
    id: '13',
    title: 'Rumah Strategis 3KT Semarang Dekat Pusat Kota',
    location: 'Semarang',
    price: 720000000,
    originalPrice: null,
    area: 110,
    image: '/images/listing-2.jpg',
    propertyType: 'Rumah',
    offerType: 'Dijual',
    bedrooms: 3,
    bathrooms: 2,
    carports: 2,
    certificate: 'SHM',
    condition: 'Bekas',
    agentName: 'Budi Santoso',
    agentVerified: true,
    views: 334,
  },
  {
    id: '14',
    title: 'Tanah Kavling SHM Makassar Dekat Mall & Bandara',
    location: 'Makassar',
    price: 850000000,
    originalPrice: null,
    area: 250,
    image: '/images/listing-3.jpg',
    propertyType: 'Tanah',
    offerType: 'Dijual',
    certificate: 'SHM',
    agentName: 'Dewi Sartika',
    agentVerified: true,
    views: 412,
  },
  {
    id: '15',
    title: 'Ruko 3 Lantai Strategis Makassar Pusat Bisnis',
    location: 'Makassar',
    price: 2100000000,
    originalPrice: 2500000000,
    area: 300,
    image: '/images/listing-1.jpg',
    propertyType: 'Ruko',
    offerType: 'Dijual & Disewa',
    isFeatured: true,
    certificate: 'HGB',
    condition: 'Baru',
    agentName: 'Dewi Sartika',
    agentVerified: true,
    views: 567,
  },
  {
    id: '16',
    title: 'Apartemen Studio Investasi ROI 12% / Tahun Bandung',
    location: 'Bandung',
    price: 380000000,
    originalPrice: null,
    area: 24,
    image: '/images/listing-2.jpg',
    propertyType: 'Kost',
    offerType: 'Dijual',
    bedrooms: 1,
    bathrooms: 1,
    certificate: 'HGB',
    condition: 'Baru',
    agentName: 'Rudi Hermawan',
    agentVerified: true,
    views: 623,
  },
  {
    id: '17',
    title: 'Kavling Cluster Eksklusif Lembang View Pegunungan',
    location: 'Lembang, Bandung',
    price: 1100000000,
    originalPrice: null,
    area: 400,
    image: '/images/listing-3.jpg',
    propertyType: 'Tanah',
    offerType: 'Dijual',
    isPremium: true,
    certificate: 'SHM',
    agentName: 'Rudi Hermawan',
    agentVerified: true,
    views: 891,
  },
  {
    id: '18',
    title: 'Rumah Minimalis Modern 2KT Siap Huni Surabaya',
    location: 'Surabaya',
    price: 320000000,
    originalPrice: 380000000,
    area: 60,
    image: '/images/listing-1.jpg',
    propertyType: 'Rumah',
    offerType: 'Dijual',
    bedrooms: 2,
    bathrooms: 1,
    carports: 1,
    certificate: 'SHM',
    condition: 'Baru',
    agentName: 'Rina Kartika',
    agentVerified: true,
    views: 234,
  },
  {
    id: '19',
    title: 'Kost Putra Eksklusif 12 Kamar Near ITS Surabaya',
    location: 'Surabaya',
    price: 2800000000,
    originalPrice: null,
    area: 350,
    image: '/images/listing-2.jpg',
    propertyType: 'Kost',
    offerType: 'Dijual',
    certificate: 'SHM',
    condition: 'Baru',
    agentName: 'Rina Kartika',
    agentVerified: true,
    views: 445,
  },
  {
    id: '20',
    title: 'Tanah SHM Pusat Kota Sleman Cocok untuk Kost',
    location: 'Depok, Sleman',
    price: 350000000,
    originalPrice: null,
    area: 120,
    image: '/images/listing-3.jpg',
    propertyType: 'Tanah',
    offerType: 'Dijual',
    certificate: 'SHM',
    agentName: 'Ahmad Fajar',
    agentVerified: false,
    views: 156,
  },
];

export const cities = [
  { name: 'Yogyakarta', image: '/images/city-yogyakarta.jpg', propertyCount: 142 },
  { name: 'Surabaya', image: '/images/city-surabaya.jpg', propertyCount: 89 },
  { name: 'Bandung', image: '/images/city-bandung.jpg', propertyCount: 76 },
  { name: 'Makassar', image: '/images/city-makassar.jpg', propertyCount: 54 },
  { name: 'Semarang', image: '/images/city-semarang.jpg', propertyCount: 43 },
  { name: 'Medan', image: '/images/city-medan.jpg', propertyCount: 38 },
];

export const propertyTypes = [
  { name: 'Rumah', count: 324, icon: '🏠' },
  { name: 'Apartemen', count: 156, icon: '🏢' },
  { name: 'Tanah', count: 89, icon: '📍' },
  { name: 'Ruko', count: 45, icon: '🏪' },
];

export const articles = [
  {
    id: '1',
    title: 'Tips Membeli Properti Impian di Era Digital',
    excerpt: 'Panduan lengkap untuk pemula yang ingin membeli properti pertama mereka.',
    image: '/images/listing-1.jpg',
    date: '15 Maret 2024',
    category: 'Tips & Panduan',
  },
  {
    id: '2',
    title: 'Trend Properti Indonesia 2024: Apa yang Harus Anda Ketahui',
    excerpt: 'Analisis mendalam tentang tren pasar properti di Indonesia tahun ini.',
    image: '/images/listing-2.jpg',
    date: '12 Maret 2024',
    category: 'Market Insights',
  },
  {
    id: '3',
    title: 'Cara Memaksimalkan ROI dari Investasi Properti',
    excerpt: 'Strategi investasi properti yang menguntungkan untuk pemula hingga profesional.',
    image: '/images/listing-3.jpg',
    date: '10 Maret 2024',
    category: 'Investment',
  },
];

export const trustMetrics = [
  { label: 'Properti Listed', value: '2.5K+' },
  { label: 'Transaksi Berhasil', value: '1.2K+' },
  { label: 'Agen Terpercaya', value: '450+' },
  { label: 'Pengguna Aktif', value: '50K+' },
];

export const howItWorks = [
  {
    step: 1,
    title: 'Cari Properti',
    description: 'Jelajahi ribuan properti tersedia dengan filter yang sesuai kebutuhan Anda.',
  },
  {
    step: 2,
    title: 'Hubungi Agen',
    description: 'Koneksi langsung dengan agen properti profesional dan terpercaya.',
  },
  {
    step: 3,
    title: 'Tinjau Properti',
    description: 'Jadwalkan kunjungan dan lihat properti dengan detail yang komprehensif.',
  },
  {
    step: 4,
    title: 'Negosiasi & Deal',
    description: 'Negosiasikan harga dan selesaikan transaksi dengan aman dan transparan.',
  },
];
